### ISSUE TITLE
Show event thumbnails in lists

### ISSUE THREAD

**Issue by christerdk** [christerdk/Malmofestivalen-for-Android#1]
When showing search results, current and upcoming event and other lists with events, it would be very nice with a thumbnail images where available.

**Comment by mirontoli** [comment]
How looks the process of getting preview images? Can we use [UriSmallImage](http://api.malmofestivalen.se/article/smygstart-med-little-dragon-och-nagra-andra-klara-bokningar/)

**Comment by christerdk** [comment]
First of all, check this out :)
The URL for the URISmallImage is: http://malmofestivalen.smugmug.com/photos/i-mHMHGHR/0/210x500/i-mHMHGHR-210x500.jpg
But try to exchange 210x500 in the URL with for example 21x50. Yes, they're re-scaling on demand - good to know! :)

As I see it the "i-mHMHGHR" is the key for the file and therefore all we really need. To keep the app speedy and also to ensure less client faults, I would prefer that we create another column in the DB containg this key. Then, in the app, we can put together an correct image URL according to our specific needs. Good with you?

I've asked around, and form what I've learned the de facto approach for doing this is to keep a list of images to load (for example max 10). This ensures that the app is not swamped with the user scrolls over a lot events very quickly.

Sub-tasks that I can identify - with suggested work delegation:
- Create new column in DB (CØ)
- Extend import of data to new column (CØ)
- Async load of images when browsing lists of events. (Anatoly)

Are you up for that?

PS. The DB centric and not API centric approach has been chosen to ensure speed (when many people are gathered and network load is high) and also to make sure, that the data used in the app is consistent (invalid data has occured, unfortunately).

**Comment by christerdk** [comment]
Ok, just a follow up after I've tried importing 50 events. The URL's are not all following the same form, in fact they're quite varied. 

I see two options:
- Either we include UriSmallImage in the DB.

or...
- We use the existing UriImage column in the DB. It contains addresses such as "http://malmofestivalen.smugmug.com/Other/Scener/60talst%C3%A4ltet/883486811_uWBG3-295x295.jpg". 
  We use that as base URL, and then replace the "295x295" with what ever size we need.

One means more data in the DB, the other means hacking together a string from existing URL. Which do you prefer? ;-)

**Comment by mirontoli** [comment]
I think if we follow the DB centric principle of the applicaiton, the thumbnails should be in the db, because it will minimize network traffic. Especially important when many people use 3G connections at the same time. What do you think?

**Comment by christerdk** [comment]
Yep, I agree. I actually have a little time over right now, so I can brew the new DB structure and fix the import. I'll give you a ping when I'm done...

**Comment by christerdk** [comment]
Updated DB structure and import now. Acts now has a UriSmallImage, which is also included in the events view.

I've created a "feature_1" branch wherein the changes have been put and I expect us to use for development of this feature.

This is inspired from the way we use feature branches on my current project. However, if there's any github de-facto style that I'm unaware of, I'd love the feedback (i'm new to github). Then we can adjust for future features.

To get some data to work with you can run MalmoFestivalDataFetcher2011 (dotnet folder). Check comments at the Main method for prerequisites. In debug mode, only 50 events are imported.

**Comment by mirontoli** [comment]
Great! To me github as a collaboration platform is new as well. I'll try [fork and pull model](http://help.github.com/send-pull-requests/). A branch for a feature, why not?

**Comment by christerdk** [comment]
Yep, cool. Minimal friction. And yes, I'm used to use branches to isolate major changes. "It works..." ;) Please keep me posted, and let me know if you have any questions or get stuck or something...

**Comment by mirontoli** [comment]
I get a strange error:
![screencap](http://grab.by/d6XS)

But it works when I run `curl http://api2011.malmofestivalen.se/json/category`

**Comment by mirontoli** [comment]
I must have been some hickup. Now it works normally

**Comment by christerdk** [comment]
Oh, btw, when you're developing pelase set Settings.IsDebug to true. This, among other things, means that no data is sent to Google Analytics... :)

**Comment by mirontoli** [comment]
I noticed that. When isdebug=false the app crashes.

**Comment by christerdk** [comment]
Could I ask you to create an issue on this, describing when and under what
circumstances the app crashes with debug=false? Then I'll look into it...
On Apr 16, 2012 8:23 PM, "Anatoly Mironov" <
reply@reply.github.com>
wrote:

**Comment by mirontoli** [comment]
I'll do that

**Comment by mirontoli** [comment]
It looks pretty good now. You'll get a pull request soon.
